### ISSUE TITLE
Duplicate UUIDs are getting generated

### ISSUE THREAD

**Issue by iducool** [daegalus/dart-uuid#130]
Hi Team,

In my code I am using `const Uuid().v4()` and it is generating duplicate IDs as per our database. I am using this to generate document id. 

I am using `4.4.0` version of the package. I have already reviewed some of the closed ticket but they are not pointing to solution which defines accurate steps of how to stop it. I don't have accurate steps to produce it so, I am unsure how would I verify that it is working that's why I am afraid of doing experiments and verify myself. 

Most probably this is happening on Flutter web because our most of the users are using web only. We are not using WASM.

**Comment by daegalus** [comment]
Ok, can you provide a small snippet of code, even if partially redacted with what you are doing with the functions?

In general, I recommend creating a single instance of `Uuid()` and using that over and over. We have had cases in past tickets where frequently recreating the `Uuid()` object can cause issues with the seed or something getting stuck on web.

so you can do `var uuid = const Uuid()` and then `var theUuid = const uuid.v4()` and see if that helps. 

In 4.5.0 we also switched the default from MathRNG to CryptoRNG, so that might help in this case. MathRNG has had a few issues with producing duplicate seeds. It was fixed in 4.4.0 but there might be other unknown issues like that. We now recommend CryptoRNG in all cases.

You can test that out in 4.4.0. Just do `const Uuid(GlobalOptions(CryptoRNG()).v4()` (you might need to adjust this a bit, I am doing it from memory). 

Give those a try and let me know if there are any other issues. I do recommend updating to the latest version if possible.
