### ISSUE TITLE
Improve the types in uuid functions

### ISSUE THREAD

**Issue by enyo** [Daegalus/dart-uuid#25]
Right now, the different `v1`, `v4`, etc.. functions return dynamic, because their return typ depends on whether a buffer has been provided.

In order to make them type safe, I suggest splitting these functions up into two functions, eg.:

```dart
String v1(/*...*/) { }

Buffer v1buffer(/*...*/) { }
```

**Comment by enyo** [comment]
Optionally, `v1` could accept a generic like this:

```dart
T v1<T>() { }

foo() {
  final result = v1<String>(/*...*/);
}
```

But I think that's not ideal.

**Comment by Daegalus** [comment]
Sorry for the delay. Thanks for bringing this up. I am doing a cleanup of the code and noticed the same thing. I realize I have to do a 2.0 release for such a change. I'm also planning to switch to pointycastle for the crypto strong uuids.

I realize if you provide a buffer, I don't need to return it, so it will return nothing in that case in the future.

**Comment by Daegalus** [comment]
For those following this ticket, sorry for the delay, but I am blocked until Pointycastle and Reflectable get fixed to work with Dart 2.0.

Currently, these tickets are blocking: https://github.com/PointyCastle/pointycastle/issues/119 https://github.com/PointyCastle/pointycastle/issues/131

https://github.com/dart-lang/reflectable/issues/136 Is the issue in Reflectable, but I think I can potentially finagle it all to work, so I will look into that in the next few days.

Just wanted to post this, so that you know I haven't forgotten about this.

**Comment by Daegalus** [comment]
I just found that there is a Random.secure constructor now for crypto secure random numbers. Thats all I was using the Crypto library for, so I will be moving to that, and it is unblocking me. I will most likely start focusing on gettin v2 going now.

**Comment by Daegalus** [comment]
version 2.0.0-rc1 is out, give it a whirl and see if it fits your needs properly. I will make it a proper release in a few days depending on bug reports.
