### ISSUE TITLE
can compare uuid 

### ISSUE THREAD

**Issue by hatemragab** [Daegalus/dart-uuid#56]
```
// Generate a v1 (time-based) id
uuid.v1(); // -> '6c84fb90-12c4-11e1-840d-7b25c5ee775a'
```
from doc it say this time based 
can I compare tow ids to know which created first ?

**Comment by Daegalus** [comment]
Theoretically, yes. The first portion of the UUID is time encoded. You would just need to reverse it. 

I can potentially add a function that does it for you, but it would be low priority compared to some other stuff I need to do.

**Comment by hatemragab** [comment]
Ok can u give me example in dart to compare?

**Comment by Daegalus** [comment]
I don't have the time right now to write that out for you. If I did, I would just implement it into the library.

Just take the first 7 bytes. Convert it to a long. Use the date time library to convert it to time. Do the same.for the other and compare. Or just compare the longs and see which one is bigger since they would be epoch time.

**Comment by hatemragab** [comment]
ok
