### ISSUE TITLE
[request] Make UuidValue more usable

### ISSUE THREAD

**Issue by giorgiofran** [Daegalus/dart-uuid#64]
Hi, I have some suggestions to make your valuable package fit better the everyday use:
- Provide an `Uint8List` parse/unparse methods. Nowadays most packages uses `Uint8List` when working with bytes. I know that it is easy converting it from a `List<int>` but I guess it would be a plus.
- Keep the value in `UuidValue` as `Uint8List` instead of `String`. This will avoid the problem that two Uuids that differs only because one has uppercases and the other has lowercases could be considered different. At least "canonicalize" the internal value to lowercases while creating an instance.
- In `UuidValue` class Implement `== operator` and `hashCode` getter. 

Thanks in advance.

**Comment by giorgiofran** [comment]
Just a simple example of what I was talking. 
This is obviously only a suggestion, a fast and furious class made just to fit my needs.
```dart
import 'dart:typed_data';
import 'package:uuid/uuid.dart' as uid;

class UuidValue extends uid.UuidValue {
  UuidValue(String uuid) : super(uuid.toLowerCase());

  UuidValue.fromByteList(Uint8List byteList, {int? offset})
      : this(uid.Uuid.unparse(byteList, offset: offset ?? 0));
  UuidValue.v4() : this(uid.Uuid().v4());

  @override
  bool operator ==(Object other) => other is UuidValue && uuid == other.uuid;

  @override
  int get hashCode => uuid.hashCode;
}
```

**Comment by Daegalus** [comment]
These are great suggestions and I will probably get these in soon. The UuidValue thing was a request also, as this library wasnt originally designed to work in a fully object oriented way, So with backwards compatibility requirements, I wasnt sure how people were going to use UuidValue and what features it needed.  So this helps, thank you for opening the request.

**Comment by Daegalus** [comment]
Ok, I added a bunch of stuff in 3.0.3. I added the hashcode, and operator overload. Added some Uint8List outputting functions. Lowercase internal (i already did this when I parsed stuff, but forgot to do it elsewhere.)

For now, I am going to keep it a String, mostly because a lot of the code assumed strings and I don't want to break backwards compatibility too much.

Also Uint8List will slowly make it back into the library. This library has been around since the beginnings of Dart. And things changed a lot. Originally this was a server-side only library, when server-side dart had some popularity (its why I got into it, as a an alternative for Node). Then someone wanted Web support. That's fine, but at the time, typed_data was server-side only, so I had to switch to `List<int>` to support web. Things changed since then, and typed_data is now on the frontend too, but I have always been conservative with the type because of how many times I have had to retype this library.

It is also why the design of this library is kind of data to modern Dart. It was designed at a time when things were very different.

I might make a 4.0.0 project/branch/milestone and completely redesign this library, but it might take a bit if I decided to do it, as I don't use dart much anymore because they kind of killed server-side back in the day. People tried to keep it alive, but even now projects like Aqueduct and such are being abandoned. A shame since I loved backend dart. I am a backend/devops developer, so I never really do any frontend, so Flutter or Web is never on my radar for anything (yet)

But I am proud of this library and my other dart libraries, so I try to keep them up to date and maintain them as much as possible, even if a bit disconnected from the community and news.

Sorry for the long post, long story short, if you want anything added, feel free to ask, or open a PR. I am always open to expand and adjust, I just assume people are happy with it if I don't get Issues/PRs. So thank you for this issue.

I will try to work on improving the library for more modern Dart design.
