### ISSUE TITLE
The UUID validation in the UuidValue constructor has no effect

### ISSUE THREAD

**Issue by FlorianUlivi** [Daegalus/dart-uuid#65]
The documentation for the constructor of the class UuidValue states:

```dart
/// Optioanlly, you can disable the validation check in the constructor
/// by setting [validate] to `true`.
```

Looking at the [code](https://github.com/Daegalus/dart-uuid/blob/43c74fb5a1cf91a63b97a967e1dd5ccc557626e4/lib/uuid.dart#L454), shouldn't the documentation say the following?

```dart
/// Optionally, you can disable the validation check in the constructor
/// by setting [validate] to `false`.
```

I am trying to pick up a new programming language with Dart, so it might escape my understanding, but what should happen if the UUID is invalid? The statement `Uuid.isValidUUID(uuid);` returns false, and it has no further consequence. The object is created with whatever is passed as `this.uuid`.

**Comment by Daegalus** [comment]
Thanks for catching that, I will fix the docs. What will happen is an error will be thrown. If you don't disable validation and invalid UUID will throw an exception. I use it in `parse` and the contructor for `UuidValue` so you cant construct a `UuidValue` with an invalid UUID as it will throw an exception when it does. If you disable the validation, it will just a best effort attempt at parsing it, or it will just set it as the value for `UuidValue`. So its up to you how to do it. 

Also `UuidValue` is a recent addition per a request, I never originally intended to make the UUIDs objects. Just strings or byte arrays, because that's all that is needed. But I had multiple requests where people were adamant for an Object, so I gave them a barebones object. It doesn't do anything special that you can't do without it.

**Comment by FlorianUlivi** [comment]
I see the use for a dedicated UUID object. That is the reason, why I started fiddling with _dart-uuid_.

> I use it in parse and the contructor for UuidValue so you cant construct ...

In current master `UuidValue` does not throw an exception. I have created a [PR](https://github.com/Daegalus/dart-uuid/pull/66) where the constructor will throw an exception analog to `parse` as well as two tests.

**Comment by Daegalus** [comment]
3.0.3 has your fix included with some changes I made from other tickets. Thank you again!
