### ISSUE TITLE
UuidValue default constructor breaking behavior

### ISSUE THREAD

**Issue by davidmartos96** [daegalus/dart-uuid#98]
Continuation of https://github.com/daegalus/dart-uuid/issues/95

@daegalus Is there any particular reason to keep that constructor const?
Why not have a constructor without arguments / factory that turns the value into lower case under the hood, same as the v3.
That small difference could be troublesome for packages that depend solely on the v3 interface but want to support v4.
On top of that, if a package updates to v4, some places of the code could be calling to the original constructor, and there is not deprecation warning, so the behavior of the package using uuid has changed.

For instance: https://github.com/mongo-dart/bson/commit/8046845680b2361bde10e098e347fd6edbfb346c

Just updating the version changed test expectations. On the source code (not the tests) there are calls to the default constructor, which now has a different behavior. 

Unless there is a good reason to keep it const, I would vote for bringing back the original behavior or deprecating the default constructor so that developers are noted about that small (but breaking) difference.

**Comment by daegalus** [comment]
That is a fair assessment. The constructor const was requested by multiple users and it's the whole reason the UuidValue class even really exists. Before then, you just used the strong or list versions.

Since UuidValue specifically holds a UuidValue string. Making it a const class improves performance, memory usage, and overall canonicalization of the UuidValue object.

Per the options you laid out, I would lean towards the deprecation route over undoing const classes. Especially since people already rely on the guarantees of a const class.

I am open to more discussion though if there are other ideas.

It is hard to cover every use case related to language features but I feel a const class covers more use cases than not.

**Comment by davidmartos96** [comment]
Yes, it's understandable. On top of that, there are many users of the library, so it can be hard to cover it all without breaking changes.

In that case I'm in favor of deprecating the default constructor, and add another one which its name implies "you know what you are doing", if creating a const UuidValue in the application is needed. 
Something like `const UuidValue.raw(this.uuid);`, `internal`, `rawValue`... And document that the value should be lowercase, which is not really mentioned in the docstring.

Thanks for listening! :smile: I just was worried that the v4 update could unexpectedly break some packages just because of depending on the automatic lowercase old behavior.

**Comment by daegalus** [comment]
Just merged your PR changes and released 4.2.0
